apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: librechat
type: Opaque
stringData:
  CREDS_KEY: "replace-with-64-char-random-hex"
  JWT_SECRET: "replace-with-64-char-random-hex"
  JWT_REFRESH_SECRET: "replace-with-64-char-random-hex"
  MEILI_MASTER_KEY: "replace-with-random-meili-master-key"
